import * as employeeService from '../Service/Employee_service.js';

export const createEmployee = async (req, res) => {
  try {
    const employee = await employeeService.createEmployee(req.body);
    res.status(201).json({ 
      success: true, 
      message: 'Employee created successfully',
      data: employee 
    });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
};

export const login = async (req, res) => {
  try {
    const { emailid, password } = req.body;
    const result = await employeeService.login(emailid, password);
    res.json(result);
  } catch (error) {
    res.status(401).json({ success: false, error: error.message });
  }
};

export const logout = async (req, res) => {
  try {
    const { sessionId } = req.body;
    const result = await employeeService.logout(sessionId);
    res.json(result);
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
};

export const getEmployees = async (req, res) => {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 9;
    const search = req.query.search || "";

    let searchCondition = {};

    if (search) {
      searchCondition.$or = [
        { name: { $regex: search, $options: "i" } },
        { phonenumber: { $regex: search, $options: "i" } },
        { emailid: { $regex: search, $options: "i" } },
        { location: { $regex: search, $options: "i" } },
        { designation: { $regex: search, $options: "i" } },
        { status: { $regex: search, $options: "i" } },
      ];
    }

    const result = await employeeService.getEmployees(
      searchCondition,
      page,
      limit
    );

    res.status(200).json({
      success: true,
      data: result.data,
      pagination: result.pagination,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
};

export const updateEmployee = async (req, res) => {
  try {
    const { id } = req.params;
    
    const employee = await employeeService.updateEmployee(id, req.body);
    
    let message = 'Employee updated successfully';
    if (employee.autoGeneratedPassword) {
      message += ` | Auto password: ${employee.autoGeneratedPassword}`;
    }
    
    res.json({ 
      success: true, 
      message,
      data: employee 
    });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
};

export const deleteEmployee = async (req, res) => {
  try {
    const { id } = req.params;
    const sessionId = req.headers["x-session-id"];

    const result = await employeeService.deleteEmployee(id, sessionId);

    res.status(200).json({
      success: true,
      message: result.message,
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message,
    });
  }
};

export const getEmployeeReport = async (req, res) => {
  try {
    const sessionId = req.headers['x-session-id'] || req.body.sessionId;
    const { fromDate, toDate } = req.query;
    const report = await employeeService.generateEmployeeWiseReport(fromDate, toDate, sessionId);
    res.json({ success: true, data: report });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};
export const updateuser = async (req, res) => {
  try {
    const { id } = req.params;
    const employeeData = req.body;

    const updatedEmployee = await employeeService. updateuser(id, employeeData);

    res.status(200).json({
      success: true,
      data: updatedEmployee,
      message: "Employee updated successfully",
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message,
    });
  }
};

// ✅ Change Password Controller (SEPARATE)
export const changePasswordController = async (req, res) => {
  try {
    const { id } = req.params;
    const { newPassword } = req.body;

    await employeeService.changePassword(id, newPassword);

    res.status(200).json({
      success: true,
      message: "Password updated successfully",
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message,
    });
  }
};